version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: spring_sample
    ports:
     - '3306:3306'
    volumes:
     - db_data:/var/lib/mysql
volumes:
  db_data: